baseURL = "https://www.kevindstevens.com"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Energy, Technology, and More"
theme = "anatole"
summarylength = 10
enableEmoji = true

# Enable Disqus
#disqusShortname = "kevindstevens-com"

# Google Analytics
#googleAnalytics = "UA-123-45"

[params]
title = "Kevin Stevens"
author = "Kevin Stevens"
description = "Energy, tech, and more"
profilePicture = "images/profile.jpg"
keywords = ""
favicon = "favicons/"
customCss = []
mainSections = ["post"]

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
[[params.socialIcons]]
icon = "fa-linkedin"
title = "Linkedin"
url = "https://linkedin.com/in/kevindavidstevens"

[[params.socialIcons]]
icon = "fa-twitter"
title = "Twitter"
url = "https://twitter.com/kevindstevens"

[[params.socialIcons]]
icon = "fa-instagram"
title = "instagram"
url = "https://www.instagram.com/kevindstevens"

[[params.socialIcons]]
icon = "fa-envelope"
title = "e-mail"
url = "mailto:kevin.stevens@inteliscapital.com"

## Menu items

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Archive"
  weight = 200
  identifier = "posts"
  url = "/post/"

[[menu.main]]
  name = "Subjects"
  weight = 300
  identifier = "tags"
  url = "/tags/"

  [[menu.main]]
  name = "Newsletter"
  weight = 400
  identifier = "newsletter"
  url = "https://thechargingstation.substack.com/"

  [[menu.main]]
  name = "Start Here"
  weight = 500
  identifier = "about"
  url = "/about/"




